version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000" # Agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root # Ensures Jenkins can access volumes

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
       - "8081:8081"
       
  gitlab:
    image: gitlab/gitlab-ce:latest  # GitLab Community Edition
    container_name: gitlab
    restart: always
    ports: 
        - "80:80"       # GitLab Web UI
        - "443:443"     # HTTPS (SSL)
        - "22:22" 
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    
volumes:
  jenkins_home:
    driver: local
  gitlab_config:
  gitlab_logs:
  gitlab_data:
    
    
